# Generated by Django 4.1.7 on 2023-03-19 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_codigo', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('cliente_id', models.IntegerField()),
                ('cliente_nombre', models.CharField(max_length=45)),
                ('cliente_ciudad', models.CharField(max_length=45)),
                ('cliente_rtn', models.IntegerField()),
                ('cliente_estado', models.CharField(max_length=45)),
                ('cliente_contacto', models.ManyToManyField(blank=True, to='appHotel.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('compra_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('compra_fecha', models.DateTimeField()),
                ('compra_rtn', models.IntegerField()),
                ('compra_descuento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('compra_subtotal_exonerado', models.DecimalField(decimal_places=2, max_digits=9)),
                ('compra_subtotal_exento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('compra_importe_gravado_18', models.DecimalField(decimal_places=2, max_digits=9)),
                ('compra_importe_gravado_15', models.DecimalField(decimal_places=2, max_digits=9)),
                ('compra_importe_gravado_4', models.DecimalField(decimal_places=2, max_digits=9)),
                ('compra_isv_18', models.DecimalField(decimal_places=2, max_digits=9)),
                ('compra_isv_15', models.DecimalField(decimal_places=2, max_digits=9)),
                ('compra_isv_4', models.DecimalField(decimal_places=2, max_digits=9)),
                ('compra_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('compra_estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra_detalle_precio_unidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('compra_detalle_cantidad', models.IntegerField()),
                ('compra_detalle_descripcion', models.TextField()),
                ('compra_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHotel.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_codigo', models.CharField(max_length=45)),
                ('empleado_nombre', models.CharField(max_length=45)),
                ('empleado_apellido', models.CharField(max_length=45)),
                ('empleado_identidad', models.PositiveBigIntegerField()),
                ('empleado_telefono', models.PositiveIntegerField()),
                ('empleado_estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('habitacion_codigo', models.TextField(primary_key=True, serialize=False)),
                ('habitacion_tipo', models.TextField(max_length=45)),
                ('habitacion_numero_personas', models.TextField(max_length=45)),
                ('habitacion_mantenimiento', models.TextField(max_length=45)),
                ('habitacion_limpieza', models.TextField(max_length=45)),
                ('habitacion_estado', models.TextField(max_length=45)),
                ('habitacion_descripcion', models.TextField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('modulo_codigo', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('modulo_nombre', models.CharField(max_length=45)),
                ('modulo_descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario_nick', models.CharField(max_length=45)),
                ('usuario_clave', models.CharField(max_length=45)),
                ('usuario_estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('venta_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('venta_nombre_cliente', models.CharField(max_length=45)),
                ('venta_fecha', models.DateTimeField()),
                ('venta_rtn', models.IntegerField()),
                ('venta_descuento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('venta_subtotal_exonerado', models.DecimalField(decimal_places=2, max_digits=9)),
                ('venta_subtotal_exento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('venta_importe_gravado_18', models.DecimalField(decimal_places=2, max_digits=9)),
                ('venta_importe_gravado_15', models.DecimalField(decimal_places=2, max_digits=9)),
                ('venta_importe_gravado_4', models.DecimalField(decimal_places=2, max_digits=9)),
                ('venta_isv_18', models.DecimalField(decimal_places=2, max_digits=9)),
                ('venta_isv_15', models.DecimalField(decimal_places=2, max_digits=9)),
                ('venta_isv_4', models.DecimalField(decimal_places=2, max_digits=9)),
                ('venta_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('venta_estado', models.CharField(max_length=45)),
                ('cliente_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHotel.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Venta_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_detalle_precioU', models.CharField(max_length=45)),
                ('venta_detalle_cantidad', models.CharField(max_length=45)),
                ('venta_detalle_descripcion', models.CharField(max_length=45)),
                ('venta_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHotel.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('reservacion_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('reservacion_nombre_cliente', models.TextField(max_length=45)),
                ('reservacion_cliente_id', models.IntegerField(verbose_name=20)),
                ('reservacion_fecha', models.DateTimeField()),
                ('reservacion_dias', models.IntegerField()),
                ('reservacion_abono', models.DecimalField(decimal_places=2, max_digits=9)),
                ('habitaciones', models.ManyToManyField(related_name='reservaciones', to='appHotel.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('registro_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('registro_nombre_cliente', models.TextField(max_length=45)),
                ('registro_nombre_empresa', models.TextField(max_length=45)),
                ('registro_rtn', models.TextField(max_length=45)),
                ('registro_telefono', models.TextField(max_length=45)),
                ('registro_id', models.TextField(max_length=45)),
                ('registro_pais', models.TextField(max_length=45)),
                ('registro_procedencia', models.TextField(max_length=45)),
                ('registro_profesion', models.TextField(max_length=45)),
                ('registro_numero_personas', models.TextField(max_length=45)),
                ('registro_niños', models.TextField(max_length=45)),
                ('registro_numero_noches', models.TextField(max_length=45)),
                ('registro_dia_entrada', models.TextField(max_length=45)),
                ('registro_dia_salida', models.TextField(max_length=45)),
                ('registro_tarifa_por_noche', models.TextField(max_length=45)),
                ('registro_total', models.TextField(max_length=45)),
                ('registro_deposito', models.TextField(max_length=45)),
                ('registro_saldo', models.TextField(max_length=45)),
                ('registro_form_de_pago', models.TextField(max_length=45)),
                ('registro_auto_marca', models.TextField(max_length=45)),
                ('registro_auto_color', models.TextField(max_length=45)),
                ('registro_firma', models.TextField(max_length=45)),
                ('habitacion_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHotel.habitacion')),
                ('habitaciones', models.ManyToManyField(related_name='registros', to='appHotel.habitacion')),
                ('venta_codigo', models.ManyToManyField(related_name='registros', to='appHotel.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedores_codigo', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('proveedores_nombre', models.CharField(max_length=45)),
                ('proveedores_telefono', models.CharField(max_length=25)),
                ('proveedores_correo', models.CharField(max_length=45)),
                ('proveedores_direccion', models.CharField(max_length=70)),
                ('compra_detalle', models.ManyToManyField(blank=True, to='appHotel.compradetalle')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_codigo', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('producto_descripcion', models.CharField(max_length=45)),
                ('producto_precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('producto_stock', models.IntegerField()),
                ('compras', models.ManyToManyField(related_name='productos', to='appHotel.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planilla_pago_dia', models.DecimalField(decimal_places=2, max_digits=9)),
                ('planilla_horas_extras', models.DecimalField(decimal_places=2, max_digits=9)),
                ('planilla_detalle', models.CharField(max_length=45)),
                ('planilla_estado', models.CharField(max_length=45)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHotel.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='proveedores_codigo',
            field=models.ManyToManyField(to='appHotel.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ManyToManyField(to='appHotel.producto'),
        ),
        migrations.CreateModel(
            name='ClienteContacto',
            fields=[
                ('cliente_contacto_telefono', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente_contacto_correo', models.CharField(max_length=45)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHotel.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='contactos',
            field=models.ManyToManyField(related_name='clientes', to='appHotel.clientecontacto'),
        ),
        migrations.CreateModel(
            name='AccesoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso_estado', models.CharField(max_length=45)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHotel.modulo')),
                ('modulos', models.ManyToManyField(related_name='accesos_usuarios', to='appHotel.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHotel.usuario')),
                ('usuarios', models.ManyToManyField(related_name='accesos_modulos', to='appHotel.usuario')),
            ],
        ),
    ]
