# Generated by Django 4.1.7 on 2023-03-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_contacto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contactos',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='habitacion_limpieza',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='habitacion_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='habitacion_numero_personas',
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='habitacion_codigo',
            field=models.TextField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='habitacion',
            table='tbl_habitacion',
        ),
    ]
