# Generated by Django 4.1.7 on 2023-03-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHotel', '0002_remove_cliente_cliente_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contactos',
            field=models.ManyToManyField(related_name='clientes', to='appHotel.clientecontacto'),
        ),
    ]
