# Generated by Django 4.1.7 on 2023-03-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHotel', '0004_cliente_cliente_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_contacto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contactos',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='tbl_cliente',
        ),
        migrations.AlterModelTable(
            name='clientecontacto',
            table='tbl_cliente_contacto',
        ),
    ]
