# Generated by Django 4.1.7 on 2023-03-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHotel', '0005_remove_cliente_cliente_contacto_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientecontacto',
            table=None,
        ),
    ]
